services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: always
    networks:
      - appnet

  api:
    build: ./api
    ports:                # ✅ FIX (VERY IMPORTANT)
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - appnet

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
    depends_on:
      redis:
        condition: service_healthy
    restart: always
    networks:
      - appnet

  frontend:
    build: ./frontend
    ports:
      - "80:3000"
    depends_on:
      api:
        condition: service_healthy
    restart: always
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
